/** Menu structure shared by the in-window menu bar (browser) and the native menu (Electron). */
import { FILTER_GROUPS, FILTERS } from '../paint/filters';
export interface MenuSpec {
  label: string;
  /** Command ids, '-' for a separator, or a submenu. */
  items: MenuItem[];
}

export type MenuItem = string | MenuSpec;

/** Tonal corrections in the reference's menu order (see paint/tonal.ts). */
const TONAL = ['brightnessContrast', 'levels', 'toneCurve', 'hsl', 'colorBalance', 'reverse', 'posterize', 'binarize', 'gradientMap'];

export const MENUS: MenuSpec[] = [
  {
    label: 'File',
    items: [
      'new',
      'open',
      '-',
      'save',
      'saveAs',
      { label: 'Save duplicate', items: ['saveDuplicate', 'saveDuplicatePsd', 'saveDuplicatePsb'] },
      '-',
      { label: 'Import', items: ['importImage', 'importAudio', 'importMovie'] },
      { label: 'Export (single layer)', items: ['export-bmp', 'export-jpeg', 'export-png', 'export-webp', 'export-tiff', 'export-tga', '-', 'export-psd', 'export-psb'] },
      { label: 'Export animation', items: ['exportSequence', 'exportCels', 'exportGif', 'exportApng', 'exportWebp', 'exportMovie', '-', 'exportSheet', 'exportAudio'] },
      '-',
      'renameCanvas',
      '-',
      'pressureSettings',
      'preferences',
    ],
  },
  {
    label: 'Edit',
    items: [
      'undo',
      'redo',
      '-',
      'cut',
      'copy',
      'paste',
      'clear',
      'clearOutside',
      '-',
      'fill',
      { label: 'Tonal correction', items: TONAL.map((t) => `tonal-${t}`) },
      '-',
      { label: 'Transform', items: ['transform', 'transformScale', 'transformRotate', 'freeTransform', 'transformDistort', 'transformSkew', 'transformPerspective', '-', 'flipLayerH', 'flipLayerV', '-', 'transformMesh'] },
      '-',
      'imageResolution',
      'canvasSize',
    ],
  },
  {
    label: 'Animation',
    items: [
      { label: 'New animation layer', items: ['newAnimationFolder', 'newCameraFolder', 'newAudioTrack'] },
      'newAnimationCel',
      '-',
      {
        label: 'Edit track',
        items: [
          'assignCel',
          'assignMultiple',
          'removeAssignedCel',
          '-',
          'setFirstDisplayed',
          'setLastDisplayed',
          'splitClip',
          'mergeClips',
          'deleteClip',
          '-',
          'trackCut',
          'trackCopy',
          'trackPaste',
          'trackDelete',
          '-',
          'enableKeyframes',
          'addKeyframe',
          'deleteKeyframe',
          'deleteAllKeyframes',
          'keyHold',
          'keyLinear',
          'keySmooth',
          'editKeyed',
          '-',
          'selectPrevCel',
          'selectNextCel',
        ],
      },
      { label: 'Animation curve', items: ['graphEditor', 'unpairHandles'] },
      { label: 'Timeline', items: ['newTimeline', 'timelineSettings', 'frameRate', 'manageTimelines', 'enableTimeline', '-', 'insertFrame', 'deleteFrame'] },
      { label: 'Move frame', items: ['firstFrame', 'prevFrame', 'nextFrame', 'lastFrame'] },
      '-',
      { label: 'Show animation cels', items: ['onionSkin', 'onionSkinSettings', '-', 'cameraView'] },
      {
        label: 'Light table',
        items: ['enableLightTable', '-', 'registerLayer', 'registerFile', 'registerOnion', '-', 'deregisterLight', 'deregisterAllLight', '-', 'centerCanvas', '-', 'lockCel'],
      },
      '-',
      'playStop',
      { label: 'Playback settings', items: ['loopPlay'] },
    ],
  },
  {
    label: 'Layer',
    items: [
      'newRasterLayer',
      { label: 'New Layer', items: ['newRasterLayer', 'newVectorLayer', '-', 'newGradientLayer', 'newFillLayer', 'newTone', '-', 'newFrameFolder'] },
      'newFolder',
      { label: 'New correction layer', items: TONAL.map((t) => `correction-${t}`) },
      'correctionSettings',
      'groupLayer',
      'ungroupLayer',
      '-',
      'duplicateLayer',
      'deleteLayer',
      'rasterize',
      '-',
      { label: 'Layer mask', items: ['maskOutside', 'maskSelection', '-', 'applyMask', 'deleteMask', '-', 'enableMask', 'linkMask', 'showMaskArea'] },
      { label: 'Ruler/Frame', items: ['perspective1', 'perspective2', 'perspective3', '-', 'showRuler', 'deleteRulers', 'drawAlongRuler', 'rulerFromVector', '-', 'divideFrame', 'frameTemplates'] },
      '-',
      'clip',
      'reference',
      'draft',
      'lockLayer',
      'lockAlpha',
      '-',
      'mergeDown',
      'mergeVisible',
      'flatten',
      '-',
      'selectLayerAbove',
      'selectLayerBelow',
      'layerUp',
      'layerDown',
    ],
  },
  {
    label: 'Select',
    items: ['selectAll', 'deselect', 'reselect', 'invertSelection', '-', 'expandSelection', 'shrinkSelection', '-', 'selectOverlappingVectors', 'selectVectorsWithin'],
  },
  {
    label: 'View',
    items: [
      'zoomIn',
      'zoomOut',
      'actualPixels',
      'fit',
      'resetDisplay',
      '-',
      'rotateLeft',
      'rotateRight',
      'rotate90',
      'rotate180',
      'rotate270',
      'resetRotation',
      'flipViewH',
      'flipViewV',
      '-',
      { label: 'Snap', items: ['snapRuler', 'snapSpecial'] },
      '-',
      'frameLines',
      'selectionLauncher',
      'selectionBorder',
    ],
  },
  { label: 'Filter', items: FILTER_GROUPS.map((g) => ({ label: g.label, items: FILTERS.filter((f) => f.group === g.id).map((f) => `filter-${f.id}`) })) },
  { label: 'Window', items: ['workspaceDefault', 'workspaceClassic', '-', 'toggleTimeline', 'animationCels', '-', 'togglePalettes', 'toggleMenuBar'] },
  { label: 'Help', items: ['shortcuts', 'about'] },
];

/** Every command id in a menu tree, depth first. */
export function menuCommandIds(items: MenuItem[] = MENUS.flatMap((m) => m.items)): string[] {
  return items.flatMap((i) => (typeof i === 'string' ? (i === '-' ? [] : [i]) : menuCommandIds(i.items)));
}
