/** Menu structure shared by the in-window menu bar (browser) and the native menu (Electron). */
export interface MenuSpec {
  label: string;
  /** Command ids; '-' is a separator. */
  items: string[];
}

export const MENUS: MenuSpec[] = [
  { label: 'File', items: ['new', 'open', '-', 'save', 'saveAs', '-', 'importImage', 'export', '-', 'renameCanvas', '-', 'preferences'] },
  {
    label: 'Edit',
    items: [
      'undo',
      'redo',
      '-',
      'cut',
      'copy',
      'paste',
      'clear',
      'clearOutside',
      '-',
      'fill',
      'hsl',
      'brightnessContrast',
      'negative',
      '-',
      'transform',
      'freeTransform',
      'flipLayerH',
      'flipLayerV',
      '-',
      'imageResolution',
      'canvasSize',
    ],
  },
  {
    label: 'Layer',
    items: [
      'newRasterLayer',
      'newFolder',
      'groupLayer',
      'ungroupLayer',
      '-',
      'duplicateLayer',
      'deleteLayer',
      '-',
      'clip',
      'reference',
      'draft',
      'lockLayer',
      'lockAlpha',
      '-',
      'mergeDown',
      'mergeVisible',
      'flatten',
      '-',
      'selectLayerAbove',
      'selectLayerBelow',
      'layerUp',
      'layerDown',
    ],
  },
  { label: 'Select', items: ['selectAll', 'deselect', 'reselect', 'invertSelection', '-', 'expandSelection', 'shrinkSelection'] },
  {
    label: 'View',
    items: [
      'zoomIn',
      'zoomOut',
      'actualPixels',
      'fit',
      'resetDisplay',
      '-',
      'rotateLeft',
      'rotateRight',
      'rotate90',
      'rotate180',
      'rotate270',
      'resetRotation',
      'flipViewH',
      'flipViewV',
      '-',
      'selectionLauncher',
      'selectionBorder',
    ],
  },
  { label: 'Filter', items: ['gaussianBlur'] },
  { label: 'Window', items: ['workspaceDefault', 'workspaceClassic', '-', 'togglePalettes', 'toggleMenuBar'] },
  { label: 'Help', items: ['shortcuts', 'about'] },
];
